version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ChzzkSongBook
      MYSQL_ROOT_PASSWORD: password123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=ChzzkSongBook;Uid=root;Pwd=password123!;
      - BaseDomain=https://www.mooldang.store
      - Chzzk__ClientId=172f9790-da2a-4322-a1ff-58e534454b8a
      - Chzzk__ClientSecret=OihzgJAhRQmsUXek-dV0h1VL_4GUqxFM3AplypS9z1k
    depends_on:
      - db
    volumes:
      - avatar_data:/app/wwwroot/images/avatars

volumes:
  db_data:
  avatar_data: