// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MooldangBot.Infrastructure.Persistence;

#nullable disable

namespace MooldangBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329055917_UpdateOmakaseEntityStructure")]
    partial class UpdateOmakaseEntityStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MooldangBot.Domain.Entities.AvatarSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DisappearTimeSeconds")
                        .HasColumnType("int");

                    b.Property<string>("InteractionImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowChat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowNickname")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StopImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("WalkingImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid")
                        .IsUnique();

                    b.ToTable("avatarsettings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CategoryValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PosterImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryId");

                    b.ToTable("chzzkcategories", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategoryAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Alias");

                    b.HasIndex("CategoryId");

                    b.ToTable("chzzkcategoryaliases", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_CommandCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("master_commandcategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "일반",
                            Name = "General",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "시스템메세지",
                            Name = "System",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "기능",
                            Name = "Feature",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_CommandFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DefaultCost")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("master_commandfeatures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DefaultCost = 0,
                            DisplayName = "텍스트 답변",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "Reply"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "공지",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "Notice"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "방제",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "Title"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "카테고리",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "Category"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "송리스트",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "SonglistToggle"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            DefaultCost = 1000,
                            DisplayName = "노래신청",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "SongRequest"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            DefaultCost = 1000,
                            DisplayName = "오마카세",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "Omakase"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            DefaultCost = 500,
                            DisplayName = "룰렛",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "Roulette"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            DefaultCost = 0,
                            DisplayName = "채팅포인트",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "ChatPoint"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "시스템 응답",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "SystemResponse"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DefaultCost = 1000,
                            DisplayName = "AI 답변",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "AI"
                        });
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_DynamicVariable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("master_dynamicvariables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "primary",
                            Description = "보유 포인트",
                            Keyword = "{포인트}",
                            QueryString = "SELECT CAST(Point AS CHAR) FROM viewerprofiles WHERE StreamerChzzkUid = @streamerUid AND ViewerUid = @viewerUid"
                        },
                        new
                        {
                            Id = 2,
                            BadgeColor = "success",
                            Description = "시청자 닉네임",
                            Keyword = "{닉네임}",
                            QueryString = "SELECT ViewerName FROM viewerprofiles WHERE StreamerChzzkUid = @streamerUid AND ViewerUid = @viewerUid"
                        },
                        new
                        {
                            Id = 3,
                            BadgeColor = "secondary",
                            Description = "현재 방송 제목",
                            Keyword = "{방제}",
                            QueryString = "METHOD:GetLiveTitle"
                        },
                        new
                        {
                            Id = 4,
                            BadgeColor = "info",
                            Description = "현재 방송 카테고리",
                            Keyword = "{카테고리}",
                            QueryString = "METHOD:GetLiveCategory"
                        },
                        new
                        {
                            Id = 5,
                            BadgeColor = "warning",
                            Description = "현재 방송 공지",
                            Keyword = "{공지}",
                            QueryString = "METHOD:GetLiveNotice"
                        },
                        new
                        {
                            Id = 6,
                            BadgeColor = "success",
                            Description = "연속 출석한 일수",
                            Keyword = "{연속출석일수}",
                            QueryString = "SELECT CAST(ConsecutiveAttendanceCount AS CHAR) FROM viewerprofiles WHERE StreamerChzzkUid = @streamerUid AND ViewerUid = @viewerUid"
                        },
                        new
                        {
                            Id = 7,
                            BadgeColor = "info",
                            Description = "누적 출석한 횟수",
                            Keyword = "{누적출석일수}",
                            QueryString = "SELECT CAST(AttendanceCount AS CHAR) FROM viewerprofiles WHERE StreamerChzzkUid = @streamerUid AND ViewerUid = @viewerUid"
                        },
                        new
                        {
                            Id = 8,
                            BadgeColor = "secondary",
                            Description = "최근 출석 날짜",
                            Keyword = "{마지막출석일}",
                            QueryString = "SELECT DATE_FORMAT(LastAttendanceAt, '%Y-%m-%d %H:%i') FROM viewerprofiles WHERE StreamerChzzkUid = @streamerUid AND ViewerUid = @viewerUid"
                        },
                        new
                        {
                            Id = 9,
                            BadgeColor = "warning",
                            Description = "현재 송리스트 활성화 여부",
                            Keyword = "{송리스트}",
                            QueryString = "METHOD:GetSonglistStatus"
                        });
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.OverlayPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid");

                    b.ToTable("overlaypresets", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.PeriodicMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid");

                    b.ToTable("periodicmessages", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.BroadcastSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TopEmotesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("TopKeywordsJson")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalChatCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("broadcastsessions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfGenosRegistry", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Frequency")
                        .HasColumnType("double");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metaphor")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Name");

                    b.ToTable("iamf_genos_registry", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfParhosCycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ParhosId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RebirthPercentage")
                        .HasColumnType("int");

                    b.Property<double>("VibrationAtDeath")
                        .HasColumnType("double");

                    b.HasKey("CycleId");

                    b.ToTable("iamf_parhos_cycles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfScenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("VibrationHz")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("iamf_scenarios", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfStreamerSetting", b =>
                {
                    b.Property<string>("ChzzkUid")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsIamfEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPersonaChatEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVisualResonanceEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("OverlayOpacity")
                        .HasColumnType("double");

                    b.Property<double>("SensitivityMultiplier")
                        .HasColumnType("double");

                    b.HasKey("ChzzkUid");

                    b.ToTable("iamf_streamer_settings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfVibrationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("EmaHz")
                        .HasColumnType("double");

                    b.Property<double>("RawHz")
                        .HasColumnType("double");

                    b.Property<double>("StabilityScore")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("iamf_vibration_logs", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.StreamerKnowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IntentAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StreamerKnowledges");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Roulette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb4_unicode_ci")
                        .HasAnnotation("Relational:JsonPropertyName", "chzzkUid");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci")
                        .HasAnnotation("Relational:JsonPropertyName", "command");

                    b.Property<int>("CostPerSpin")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "costPerSpin");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid");

                    b.HasIndex("ChzzkUid", "Id")
                        .IsDescending(false, true);

                    b.ToTable("roulettes", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<bool>("IsMission")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isMission");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "itemName");

                    b.Property<double>("Probability")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "probability");

                    b.Property<double>("Probability10x")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "probability10x");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "rouletteId");

                    b.HasKey("Id");

                    b.HasIndex("RouletteId");

                    b.ToTable("rouletteitems", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "items");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsMission")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int");

                    b.Property<string>("RouletteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ViewerNickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.HasKey("Id");

                    b.HasIndex("RouletteId");

                    b.HasIndex("ChzzkUid", "Status", "Id")
                        .IsDescending(false, false, true);

                    b.ToTable("roulettelogs", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SharedComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid");

                    b.ToTable("sharedcomponents", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SongBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid", "Id")
                        .IsDescending(false, true);

                    b.ToTable("songbooks", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SongQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid");

                    b.HasIndex("ChzzkUid", "Id");

                    b.HasIndex("ChzzkUid", "Status", "CreatedAt");

                    b.ToTable("songqueues", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SonglistSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CompleteCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid", "IsActive");

                    b.ToTable("songlistsessions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ManagerChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StreamerChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.HasKey("Id");

                    b.HasIndex("ManagerChzzkUid");

                    b.ToTable("streamermanagers", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerOmakaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<int>("Count")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasIndex("ChzzkUid", "MenuId");

                    b.ToTable("streameromakases", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveOverlayPresetId")
                        .HasColumnType("int");

                    b.Property<string>("ApiClientId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApiClientSecret")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ApiRedirectUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AttendanceCommands")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AttendanceReply")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BotAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("BotChzzkUid")
                        .HasColumnType("longtext");

                    b.Property<string>("BotNickname")
                        .HasColumnType("longtext");

                    b.Property<string>("BotRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BotTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChzzkAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ChzzkRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("DesignSettingsJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBotEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOmakaseEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NoticeMemo")
                        .HasColumnType("longtext");

                    b.Property<string>("OmakaseCommand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OmakaseCount")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("OmakasePrice")
                        .HasColumnType("int");

                    b.Property<string>("PointCheckCommand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PointCheckReply")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PointPerAttendance")
                        .HasColumnType("int");

                    b.Property<int>("PointPerChat")
                        .HasColumnType("int");

                    b.Property<int>("PointPerDonation1000")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SongCommand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SongPrice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid")
                        .IsUnique();

                    b.ToTable("streamerprofiles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("KeyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BotAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("BotRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KeyName");

                    b.ToTable("systemsettings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.UnifiedCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("chzzkuid")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("keyword")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid", "Keyword")
                        .IsUnique();

                    b.HasIndex("ChzzkUid", "TargetId");

                    b.ToTable("unifiedcommands", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ViewerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceCount")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveAttendanceCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAttendanceAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Points")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("StreamerChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("ViewerUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerChzzkUid", "Points");

                    b.HasIndex("StreamerChzzkUid", "ViewerUid")
                        .IsUnique();

                    b.ToTable("viewerprofiles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategoryAlias", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.ChzzkCategory", "Category")
                        .WithMany("Aliases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_CommandFeature", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.Master_CommandCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteItem", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.Roulette", "Roulette")
                        .WithMany("Items")
                        .HasForeignKey("RouletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roulette");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategory", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Roulette", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
