// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MooldangBot.Infrastructure.Persistence;

#nullable disable

namespace MooldangBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.AvatarSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisappearTimeSeconds")
                        .HasColumnType("int");

                    b.Property<string>("InteractionImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowChat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowNickname")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StopImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("WalkingImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId")
                        .IsUnique();

                    b.ToTable("overlay_avatar_settings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategory", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CategoryValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PosterImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryId");

                    b.ToTable("sys_chzzk_categories", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategoryAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Alias");

                    b.HasIndex("CategoryId");

                    b.ToTable("sys_chzzk_category_aliases", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.GlobalViewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ViewerUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViewerUidHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ViewerUidHash")
                        .IsUnique();

                    b.ToTable("core_global_viewers", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_CommandCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("func_cmd_master_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "일반",
                            Name = "General",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "시스템메세지",
                            Name = "System",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "기능",
                            Name = "Feature",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_CommandFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DefaultCost")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("func_cmd_master_features", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DefaultCost = 0,
                            DisplayName = "텍스트 답변",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "Reply"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "공지",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "Notice"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "방제",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "Title"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "카테고리",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "Category"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "송리스트",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "SonglistToggle"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            DefaultCost = 1000,
                            DisplayName = "노래신청",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "SongRequest"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            DefaultCost = 1000,
                            DisplayName = "오마카세",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "Omakase"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            DefaultCost = 500,
                            DisplayName = "룰렛",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "Roulette"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            DefaultCost = 0,
                            DisplayName = "채팅포인트",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "ChatPoint"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DefaultCost = 0,
                            DisplayName = "시스템 응답",
                            IsEnabled = true,
                            RequiredRole = "Manager",
                            TypeName = "SystemResponse"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DefaultCost = 1000,
                            DisplayName = "AI 답변",
                            IsEnabled = true,
                            RequiredRole = "Viewer",
                            TypeName = "AI"
                        });
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_DynamicVariable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("func_cmd_master_variables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "primary",
                            Description = "보유 포인트",
                            Keyword = "{포인트}",
                            QueryString = "SELECT CAST(vp.Points AS CHAR) FROM view_profiles vp JOIN core_streamer_profiles sp ON vp.StreamerProfileId = sp.Id JOIN core_global_viewers gv ON vp.GlobalViewerId = gv.Id WHERE sp.ChzzkUid = @streamerUid AND gv.ViewerUidHash = @viewerHash"
                        },
                        new
                        {
                            Id = 2,
                            BadgeColor = "success",
                            Description = "시청자 닉네임",
                            Keyword = "{닉네임}",
                            QueryString = "SELECT vp.Nickname FROM view_profiles vp JOIN core_streamer_profiles sp ON vp.StreamerProfileId = sp.Id JOIN core_global_viewers gv ON vp.GlobalViewerId = gv.Id WHERE sp.ChzzkUid = @streamerUid AND gv.ViewerUidHash = @viewerHash"
                        },
                        new
                        {
                            Id = 3,
                            BadgeColor = "secondary",
                            Description = "현재 방송 제목",
                            Keyword = "{방제}",
                            QueryString = "METHOD:GetLiveTitle"
                        },
                        new
                        {
                            Id = 4,
                            BadgeColor = "info",
                            Description = "현재 방송 카테고리",
                            Keyword = "{카테고리}",
                            QueryString = "METHOD:GetLiveCategory"
                        },
                        new
                        {
                            Id = 5,
                            BadgeColor = "warning",
                            Description = "현재 방송 공지",
                            Keyword = "{공지}",
                            QueryString = "METHOD:GetLiveNotice"
                        },
                        new
                        {
                            Id = 6,
                            BadgeColor = "success",
                            Description = "연속 출석한 일수",
                            Keyword = "{연속출석일수}",
                            QueryString = "SELECT CAST(vp.ConsecutiveAttendanceCount AS CHAR) FROM view_profiles vp JOIN core_streamer_profiles sp ON vp.StreamerProfileId = sp.Id JOIN core_global_viewers gv ON vp.GlobalViewerId = gv.Id WHERE sp.ChzzkUid = @streamerUid AND gv.ViewerUidHash = @viewerHash"
                        },
                        new
                        {
                            Id = 7,
                            BadgeColor = "info",
                            Description = "누적 출석한 횟수",
                            Keyword = "{누적출석일수}",
                            QueryString = "SELECT CAST(vp.AttendanceCount AS CHAR) FROM view_profiles vp JOIN core_streamer_profiles sp ON vp.StreamerProfileId = sp.Id JOIN core_global_viewers gv ON vp.GlobalViewerId = gv.Id WHERE sp.ChzzkUid = @streamerUid AND gv.ViewerUidHash = @viewerHash"
                        },
                        new
                        {
                            Id = 8,
                            BadgeColor = "secondary",
                            Description = "최근 출석 날짜",
                            Keyword = "{마지막출석일}",
                            QueryString = "SELECT DATE_FORMAT(vp.LastAttendanceAt, '%Y-%m-%d %H:%i') FROM view_profiles vp JOIN core_streamer_profiles sp ON vp.StreamerProfileId = sp.Id JOIN core_global_viewers gv ON vp.GlobalViewerId = gv.Id WHERE sp.ChzzkUid = @streamerUid AND gv.ViewerUidHash = @viewerHash"
                        },
                        new
                        {
                            Id = 10,
                            BadgeColor = "warning",
                            Description = "현재 송리스트 활성화 여부",
                            Keyword = "{송리스트}",
                            QueryString = "METHOD:GetSonglistStatus"
                        });
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.OverlayPreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("overlay_presets", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.PeriodicMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("view_periodic_messages", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.BroadcastSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TopEmotesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("TopKeywordsJson")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalChatCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "IsActive");

                    b.ToTable("sys_broadcast_sessions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfGenosRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Frequency")
                        .HasColumnType("double");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metaphor")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("iamf_genos_registry", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfParhosCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RebirthPercentage")
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("VibrationAtDeath")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "CycleId")
                        .IsUnique();

                    b.ToTable("iamf_parhos_cycles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfScenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("VibrationHz")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("iamf_scenarios", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfStreamerSetting", b =>
                {
                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIamfEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPersonaChatEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVisualResonanceEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("OverlayOpacity")
                        .HasColumnType("double");

                    b.Property<double>("SensitivityMultiplier")
                        .HasColumnType("double");

                    b.HasKey("StreamerProfileId");

                    b.ToTable("iamf_streamer_settings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfVibrationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("EmaHz")
                        .HasColumnType("double");

                    b.Property<double>("RawHz")
                        .HasColumnType("double");

                    b.Property<double>("StabilityScore")
                        .HasColumnType("double");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "CreatedAt");

                    b.ToTable("iamf_vibration_logs", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.StreamerKnowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IntentAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "Keyword");

                    b.ToTable("streamer_knowledges", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Roulette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "deletedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "streamerProfileId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.HasIndex("StreamerProfileId", "Id")
                        .IsDescending(false, true);

                    b.ToTable("func_roulette_main", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<bool>("IsMission")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isMission");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "itemName");

                    b.Property<double>("Probability")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "probability");

                    b.Property<double>("Probability10x")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "probability10x");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "rouletteId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("RouletteId");

                    b.ToTable("func_roulette_items", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "items");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMission")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int");

                    b.Property<int?>("RouletteItemId")
                        .HasColumnType("int");

                    b.Property<string>("RouletteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ViewerNickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("RouletteId");

                    b.HasIndex("RouletteItemId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "Status", "Id")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_RouletteLog_Status_Cursor");

                    b.ToTable("func_roulette_logs", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteSpin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViewerNickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId");

                    b.HasIndex("IsCompleted", "ScheduledTime");

                    b.ToTable("func_roulette_spins", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SharedComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("overlay_components", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SongBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "Id")
                        .IsDescending(false, true);

                    b.ToTable("song_book_main", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SongQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId");

                    b.HasIndex("StreamerProfileId", "Id");

                    b.HasIndex("StreamerProfileId", "Status", "CreatedAt");

                    b.HasIndex("StreamerProfileId", "Status", "Id")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_SongQueue_Status_Cursor");

                    b.ToTable("song_list_queues", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SonglistSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompleteCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "IsActive");

                    b.ToTable("song_list_sessions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId")
                        .IsUnique();

                    b.ToTable("core_streamer_managers", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerOmakaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("song_list_omakases", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveOverlayPresetId")
                        .HasColumnType("int");

                    b.Property<string>("ApiClientId")
                        .HasColumnType("longtext");

                    b.Property<string>("ApiClientSecret")
                        .HasColumnType("longtext");

                    b.Property<string>("ApiRedirectUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("AttendanceCommands")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AttendanceReply")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BotAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("BotChzzkUid")
                        .HasColumnType("longtext");

                    b.Property<string>("BotNickname")
                        .HasColumnType("longtext");

                    b.Property<string>("BotRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("BotTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChzzkAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ChzzkRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesignSettingsJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMasterEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOmakaseEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NoticeMemo")
                        .HasColumnType("longtext");

                    b.Property<string>("OmakaseCommand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OmakaseCount")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("OmakasePrice")
                        .HasColumnType("int");

                    b.Property<string>("PointCheckCommand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PointCheckReply")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PointPerAttendance")
                        .HasColumnType("int");

                    b.Property<int>("PointPerChat")
                        .HasColumnType("int");

                    b.Property<int>("PointPerDonation1000")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SongCommand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SongPrice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid")
                        .IsUnique();

                    b.ToTable("core_streamer_profiles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<string>("KeyName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BotAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("BotRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("KeyValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KeyName");

                    b.ToTable("sys_settings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.UnifiedCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("keyword")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<int>("MasterCommandFeatureId")
                        .HasColumnType("int");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MasterCommandFeatureId");

                    b.HasIndex("StreamerProfileId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UnifiedCommand_CursorPaging");

                    b.HasIndex("StreamerProfileId", "Keyword")
                        .IsUnique();

                    b.HasIndex("StreamerProfileId", "TargetId");

                    b.ToTable("func_cmd_unified", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ViewerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceCount")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveAttendanceCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastAttendanceAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<int>("Points")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId")
                        .IsUnique();

                    b.HasIndex("StreamerProfileId", "Points");

                    b.ToTable("view_profiles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.AvatarSetting", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithOne()
                        .HasForeignKey("MooldangBot.Domain.Entities.AvatarSetting", "StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategoryAlias", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.ChzzkCategory", "Category")
                        .WithMany("Aliases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Master_CommandFeature", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.Master_CommandCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.OverlayPreset", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.PeriodicMessage", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.BroadcastSession", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfGenosRegistry", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfParhosCycle", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfScenario", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfStreamerSetting", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithOne()
                        .HasForeignKey("MooldangBot.Domain.Entities.Philosophy.IamfStreamerSetting", "StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfVibrationLog", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.StreamerKnowledge", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Roulette", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteItem", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.Roulette", "Roulette")
                        .WithMany("Items")
                        .HasForeignKey("RouletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roulette");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteLog", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.GlobalViewer", "GlobalViewer")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.RouletteItem", "RouletteItem")
                        .WithMany()
                        .HasForeignKey("RouletteItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalViewer");

                    b.Navigation("RouletteItem");

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.RouletteSpin", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.GlobalViewer", "GlobalViewer")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalViewer");

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SharedComponent", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SongBook", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SongQueue", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.GlobalViewer", "GlobalViewer")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalViewer");

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SonglistSession", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerManager", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.GlobalViewer", "GlobalViewer")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalViewer");

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.StreamerOmakaseItem", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.UnifiedCommand", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.Master_CommandFeature", "MasterFeature")
                        .WithMany()
                        .HasForeignKey("MasterCommandFeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterFeature");

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ViewerProfile", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.GlobalViewer", "GlobalViewer")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.StreamerProfile", "StreamerProfile")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalViewer");

                    b.Navigation("StreamerProfile");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.ChzzkCategory", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Roulette", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
