// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MooldangBot.Infrastructure.Persistence;

#nullable disable

namespace MooldangBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502115050_InitialPascalCase")]
    partial class InitialPascalCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysAvatarSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisappearTimeSeconds")
                        .HasColumnType("int");

                    b.Property<string>("InteractionImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowChat")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowNickname")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StopImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("WalkingImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId")
                        .IsUnique();

                    b.ToTable("SysAvatarSettings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogChatInteractions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCommand")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SenderNickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsCommand", "CreatedAt");

                    b.HasIndex("StreamerProfileId", "CreatedAt");

                    b.ToTable("LogChatInteractions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysChzzkCategories", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CategoryValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PosterImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CategoryId");

                    b.ToTable("SysChzzkCategories", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysChzzkCategoryAliases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Alias");

                    b.HasIndex("CategoryId");

                    b.ToTable("SysChzzkCategoryAliases", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogCommandExecutions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Arguments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DonationAmount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RawMessage")
                        .HasColumnType("longtext");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("Keyword", "CreatedAt");

                    b.HasIndex("StreamerProfileId", "CreatedAt");

                    b.ToTable("LogCommandExecutions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.CoreGlobalViewers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("PreviousNickname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ViewerUid")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ViewerUidHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .HasDatabaseName("IX_GlobalViewer_Nickname");

                    b.HasIndex("ViewerUid")
                        .IsUnique()
                        .HasDatabaseName("IX_GlobalViewer_ViewerUid");

                    b.HasIndex("ViewerUidHash")
                        .IsUnique()
                        .HasDatabaseName("IX_GlobalViewer_ViewerUidHash");

                    b.ToTable("CoreGlobalViewers", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogRouletteStats", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int");

                    b.Property<double>("TheoreticalProbability")
                        .HasColumnType("double");

                    b.Property<int>("TotalSpins")
                        .HasColumnType("int");

                    b.Property<int>("WinCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RouletteId", "ItemName")
                        .IsUnique();

                    b.ToTable("LogRouletteStats", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongMasterLibrary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Album")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Alias")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ArtistChosung")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LyricsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MrUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("SongLibraryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TitleChosung")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YoutubeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Album");

                    b.HasIndex("Alias");

                    b.HasIndex("ArtistChosung");

                    b.HasIndex("Category");

                    b.HasIndex("SongLibraryId")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.HasIndex("TitleChosung");

                    b.HasIndex("YoutubeUrl");

                    b.ToTable("FuncSongMasterLibrary", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongMasterStaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ArtistChosung")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LyricsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("SongLibraryId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SourceType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TitleChosung")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("YoutubeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistChosung");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SongLibraryId")
                        .IsUnique();

                    b.HasIndex("TitleChosung");

                    b.HasIndex("YoutubeUrl");

                    b.ToTable("FuncSongMasterStaging", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysOverlayPresets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("SysOverlayPresets", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysPeriodicMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("SysPeriodicMessages", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.LogBroadcastHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BroadcastSessionId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BroadcastSessionId", "LogDate");

                    b.ToTable("LogBroadcastHistory", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.SysBroadcastSessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentCategory")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CurrentTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InitialCategory")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InitialTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TopEmotesJson")
                        .HasColumnType("longtext");

                    b.Property<string>("TopKeywordsJson")
                        .HasColumnType("longtext");

                    b.Property<int>("TotalChatCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "IsActive");

                    b.ToTable("SysBroadcastSessions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfGenosRegistry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Frequency")
                        .HasColumnType("double");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metaphor")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("IamfGenosRegistry", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfParhosCycles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RebirthPercentage")
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("VibrationAtDeath")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "CycleId")
                        .IsUnique();

                    b.ToTable("IamfParhosCycles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfScenarios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("VibrationHz")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("IamfScenarios", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfStreamerSettings", b =>
                {
                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsIamfEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPersonaChatEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVisualResonanceEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("OverlayOpacity")
                        .HasColumnType("double");

                    b.Property<double>("SensitivityMultiplier")
                        .HasColumnType("double");

                    b.HasKey("StreamerProfileId");

                    b.ToTable("IamfStreamerSettings", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.LogIamfVibrations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("EmaHz")
                        .HasColumnType("double");

                    b.Property<double>("RawHz")
                        .HasColumnType("double");

                    b.Property<double>("StabilityScore")
                        .HasColumnType("double");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "CreatedAt");

                    b.ToTable("LogIamfVibrations", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.SysStreamerKnowledges", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IntentAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "Keyword");

                    b.ToTable("SysStreamerKnowledges", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogPointDailySummaries", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TopCommandStatsJson")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("TotalEarned")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSpent")
                        .HasColumnType("bigint");

                    b.Property<int>("UniqueViewerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "Date")
                        .IsUnique();

                    b.ToTable("LogPointDailySummaries", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogPointTransactions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId", "CreatedAt");

                    b.HasIndex("StreamerProfileId", "CreatedAt");

                    b.ToTable("LogPointTransactions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncRouletteMain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "deletedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "streamerProfileId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.HasIndex("StreamerProfileId", "Id")
                        .IsDescending(false, true);

                    b.ToTable("FuncRouletteMain", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncRouletteItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isActive");

                    b.Property<bool>("IsMission")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "isMission");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "itemName");

                    b.Property<double>("Probability")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "probability");

                    b.Property<double>("Probability10x")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "probability10x");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "rouletteId");

                    b.Property<string>("SoundUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "soundUrl");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("Relational:JsonPropertyName", "template");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<bool>("UseDefaultSound")
                        .HasColumnType("tinyint(1)")
                        .HasAnnotation("Relational:JsonPropertyName", "useDefaultSound");

                    b.HasKey("Id");

                    b.HasIndex("RouletteId");

                    b.ToTable("FuncRouletteItems", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "items");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogRouletteResults", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMission")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int");

                    b.Property<int?>("RouletteItemId")
                        .HasColumnType("int");

                    b.Property<string>("RouletteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("RouletteId");

                    b.HasIndex("RouletteItemId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "Status", "Id")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_RouletteLog_Status_Cursor");

                    b.ToTable("LogRouletteResults", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncRouletteSpins", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RouletteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId");

                    b.HasIndex("IsCompleted", "ScheduledTime");

                    b.ToTable("FuncRouletteSpins", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysSharedComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("SysSharedComponents", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongBooks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Alias")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Artist")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequestable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSungAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LyricsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("MrUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Pitch")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Proficiency")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("int");

                    b.Property<int>("SingCount")
                        .HasColumnType("int")
                        .HasColumnName("sing_count");

                    b.Property<long?>("SongLibraryId")
                        .HasColumnType("bigint");

                    b.Property<int>("SongNo")
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TitleChosung")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Alias");

                    b.HasIndex("Category");

                    b.HasIndex("IsRequestable");

                    b.HasIndex("SongLibraryId");

                    b.HasIndex("Title");

                    b.HasIndex("TitleChosung");

                    b.HasIndex("StreamerProfileId", "Id");

                    b.HasIndex("StreamerProfileId", "SongNo")
                        .IsUnique();

                    b.ToTable("FuncSongBooks", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongListQueues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Cost")
                        .HasColumnType("int");

                    b.Property<int?>("CostType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Pitch")
                        .HasColumnType("longtext");

                    b.Property<string>("RequesterNickname")
                        .HasColumnType("longtext");

                    b.Property<int?>("SongBookId")
                        .HasColumnType("int");

                    b.Property<long>("SongLibraryId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VideoId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("SongBookId");

                    b.HasIndex("SongLibraryId");

                    b.HasIndex("StreamerProfileId");

                    b.HasIndex("StreamerProfileId", "Id");

                    b.HasIndex("StreamerProfileId", "Status", "CreatedAt");

                    b.HasIndex("StreamerProfileId", "Status", "Id")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_SongQueue_Status_Cursor");

                    b.ToTable("FuncSongListQueues", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongListSessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompleteCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RequestCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "IsActive");

                    b.ToTable("FuncSongListSessions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSoundAssets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SoundUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("FuncSoundAssets");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.CoreStreamerManagers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId")
                        .IsUnique();

                    b.ToTable("CoreStreamerManagers", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongListOmakases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("FuncSongListOmakases", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysStreamerPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PreferenceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "PreferenceKey")
                        .IsUnique();

                    b.ToTable("SysStreamerPreferences", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.CoreStreamerProfiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveOverlayPresetId")
                        .HasColumnType("int");

                    b.Property<string>("BotNickname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ChzzkAccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ChzzkRefreshToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ChzzkUid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesignSettingsJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAutoAccumulateDonation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMasterEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NoticeMemo")
                        .HasColumnType("longtext");

                    b.Property<string>("OverlayToken")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("OverlayTokenVersion")
                        .HasColumnType("int");

                    b.Property<int>("PointPerAttendance")
                        .HasColumnType("int");

                    b.Property<int>("PointPerChat")
                        .HasColumnType("int");

                    b.Property<int>("PointPerDonation1000")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RedirectUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Slug")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ChzzkUid")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CoreStreamerProfiles", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongStreamerLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Artist")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LyricsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<long>("SongLibraryId")
                        .HasColumnType("bigint");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TitleChosung")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("YoutubeTitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SongLibraryId")
                        .IsUnique();

                    b.HasIndex("StreamerProfileId", "SongLibraryId")
                        .IsUnique();

                    b.ToTable("FuncSongStreamerLibrary", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncCmdUnified", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("utf8mb4_unicode_ci");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RequiresSpace")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StreamerProfileId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_UnifiedCommand_CursorPaging");

                    b.HasIndex("StreamerProfileId", "TargetId");

                    b.HasIndex("StreamerProfileId", "Keyword", "FeatureType");

                    b.HasIndex("StreamerProfileId", "Keyword", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_Command_Search");

                    b.ToTable("FuncCmdUnified", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncViewerDonations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<long>("TotalDonated")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId")
                        .IsUnique();

                    b.ToTable("FuncViewerDonations", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncViewerDonationHistories", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("json");

                    b.Property<string>("PlatformTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("PlatformTransactionId")
                        .IsUnique();

                    b.HasIndex("StreamerProfileId");

                    b.ToTable("FuncViewerDonationHistories", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncViewerPoints", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId")
                        .IsUnique();

                    b.ToTable("FuncViewerPoints", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.CoreViewerRelations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttendanceCount")
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveAttendanceCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FirstVisitAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GlobalViewerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastAttendanceAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastChatAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StreamerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalViewerId");

                    b.HasIndex("StreamerProfileId", "GlobalViewerId")
                        .IsUnique();

                    b.ToTable("CoreViewerRelations", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Infrastructure.Sagas.SysSagaCommandExecutions", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ChargedAmount")
                        .HasColumnType("int");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StreamerUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ViewerNickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViewerUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrentState");

                    b.ToTable("SysSagaCommandExecutions", (string)null);
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysAvatarSettings", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithOne()
                        .HasForeignKey("MooldangBot.Domain.Entities.SysAvatarSettings", "StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogChatInteractions", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysChzzkCategoryAliases", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.SysChzzkCategories", "Category")
                        .WithMany("Aliases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogCommandExecutions", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogRouletteStats", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.FuncRouletteMain", "FuncRouletteMain")
                        .WithMany()
                        .HasForeignKey("RouletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuncRouletteMain");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysOverlayPresets", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysPeriodicMessages", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.LogBroadcastHistory", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.Philosophy.SysBroadcastSessions", "SysBroadcastSessions")
                        .WithMany()
                        .HasForeignKey("BroadcastSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SysBroadcastSessions");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.SysBroadcastSessions", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfGenosRegistry", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfParhosCycles", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfScenarios", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.IamfStreamerSettings", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithOne()
                        .HasForeignKey("MooldangBot.Domain.Entities.Philosophy.IamfStreamerSettings", "StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.LogIamfVibrations", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.Philosophy.SysStreamerKnowledges", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogPointDailySummaries", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogPointTransactions", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncRouletteMain", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncRouletteItems", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.FuncRouletteMain", "FuncRouletteMain")
                        .WithMany("Items")
                        .HasForeignKey("RouletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuncRouletteMain");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.LogRouletteResults", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.FuncRouletteItems", "FuncRouletteItems")
                        .WithMany()
                        .HasForeignKey("RouletteItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("FuncRouletteItems");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncRouletteSpins", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysSharedComponents", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongBooks", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongListQueues", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MooldangBot.Domain.Entities.FuncSongBooks", "FuncSongBooks")
                        .WithMany()
                        .HasForeignKey("SongBookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("FuncSongBooks");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongListSessions", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSoundAssets", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.CoreStreamerManagers", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongListOmakases", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysStreamerPreferences", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncSongStreamerLibrary", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncCmdUnified", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncViewerDonations", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncViewerDonationHistories", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncViewerPoints", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.CoreViewerRelations", b =>
                {
                    b.HasOne("MooldangBot.Domain.Entities.CoreGlobalViewers", "CoreGlobalViewers")
                        .WithMany()
                        .HasForeignKey("GlobalViewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MooldangBot.Domain.Entities.CoreStreamerProfiles", "CoreStreamerProfiles")
                        .WithMany()
                        .HasForeignKey("StreamerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreGlobalViewers");

                    b.Navigation("CoreStreamerProfiles");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.SysChzzkCategories", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("MooldangBot.Domain.Entities.FuncRouletteMain", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
